### PR TITLE
Make treeof work with chaperone and impersonator contracts.

### PR DESCRIPTION
**Pull request by endobson**
Closes PR13504.

I didn't see any tests so didn't add any, but tested manually.

### CODE REVIEW

**Comment by rfindler** [comment]
I have to wonder: how is this used?

**Comment by samth** [comment]
It feels like we could have a version of `recursive-contract` like:

```
(recursive-contract c #:same-as c*)
```

**Comment by endobson** [comment]
@rfindler I believe in the main distribution it is used by plot. I don't remember why I wanted this when I filed the bugs years ago. Also how does submitting tests and code across repos work? Submit code then tests? Is there anything to make sure that it is 'atomic' for other people later?

@samth I agree, I've had to write this logic a couple of times.

**Comment by rfindler** [comment]
I don't know about submitting things across repos. Why are you asking that?

**Comment by endobson** [comment]
Because I got confused about which PR comments were on. I should wake up before reading emails.

**Comment by rfindler** [comment]
Oh! That makes sense. I think the tests on the other one are in the other repo too, so I think we're good.

**Comment by samth** [comment]
This still seems like a good idea to merge. Do you agree, @rfindler?

**Comment by rfindler** [comment]
Yes. Thanks!

**Pull request merged**
