### PR TITLE
add list*/c and improve rename-contract

### PR DESCRIPTION
**Pull request by AlexKnauth**
P.S. where are the tests for these?

### CODE REVIEW

**Comment by AlexKnauth** [comment]
How does this look?

**Comment by samth** [comment]
Who's the original author of `rename-contract`?

**Comment by AlexKnauth** [comment]
@rmculpepper ?
https://github.com/racket/unstable-contract-lib/blob/master/unstable/contract.rkt#L15

**Comment by rmculpepper** [comment]
Yes, `rename-contract` was mine. The changes look plausible, but I don't have any experience with `contract-stronger?`.

**Comment by stamourv** [comment]
The changes to `rename-contract` look good to me.

I would prefer to avoid adding new bindings to any `unstable` collection, though. I've been working to merge the most used/useful parts of it into "better" parts of the standard library, and move the rest out of the main distribution. Any new bindings will have to follow one of those paths when I get around to `unstable/contract`. So I think we should decide whether `list*/c` is something we want, in which case we should move it to `racket/contract` or something, or whether it's not something we want for the core libraries, and leave it out altogether.

Ceterum censeo, unstable delenda est. :)

**Comment by AlexKnauth** [comment]
@stamourv Should I just include the improve rename-contract commit then?

**Comment by AlexKnauth** [comment]
See https://github.com/racket/unstable-contract-lib/pull/4

**Comment by stamourv** [comment]
If you're still interested in adding `list*/c`, could you submit a PR to the main `racket` repo, to add it to `racket/contract`?
Thanks!

**Pull request closed without merging**
